class UserModel {
  String? token;
  bool? islogin;

  UserModel({this.token, this.islogin});

  UserModel.fromJson(Map<String, dynamic> json) {
    token = json['token'];
    islogin = json['islogin'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['token'] = this.token;
    data['islogin'] = this.islogin;
    return data;
  }
}

//send the reques on the postman by entering the url and the endpoint 
// a token will be recieved then add that token to website JSON to dart
// this calss will be generated by that
// then add this in the models folder
//then create controllers